"""Automatic web tunnel manager for Onshape MCP.
Spawns the local SSE server and exposes a secure public HTTPS endpoint
(via Cloudflare Quick Tunnels or Localtunnel) with zero configuration.

Allows web AIs (ChatGPT Web, LibreChat, Open WebUI) to connect instantly.
"""

from __future__ import annotations

import json
import os
import re
import secrets
import shutil
import socket
import subprocess
import sys
import threading
import time
from typing import Any

from .config import settings


def require_token(app: Any, token: str) -> Any:
    """Wrap an ASGI app so every request must present `token`.

    This server drives a browser logged into the user's Onshape account,
    so an open endpoint is an account takeover. Clients send
    `Authorization: Bearer <token>` or `?token=<token>` — ChatGPT
    connectors only take a URL, hence the query form.

    Pure ASGI, not BaseHTTPMiddleware: the latter buffers responses and
    would stall the SSE stream this whole transport depends on.
    """
    from urllib.parse import parse_qs, quote

    # The SSE stream's first event tells the client which URL to POST
    # its messages to, and that URL is generated by the MCP transport
    # without our token. The client uses it verbatim, so its very first
    # POST would 401 and the handshake would hang forever. Append the
    # token to the advertised endpoint.
    suffix = f"&token={quote(token, safe='')}".encode()

    def _add_token_to_endpoint(body: bytes) -> bytes:
        if b"data: /" not in body or b"token=" in body:
            return body
        out = bytearray()
        for line in body.split(b"\n"):
            if line.startswith(b"data: /") and b"session_id=" in line:
                line = line.rstrip(b"\r") + suffix
            out += line + b"\n"
        return bytes(out[:-1])

    async def gated(scope: dict, receive: Any, send: Any) -> None:
        if scope["type"] != "http":
            return await app(scope, receive, send)
        supplied = ""
        for key, value in scope.get("headers", []):
            if key == b"authorization":
                header = value.decode("latin-1")
                if header.lower().startswith("bearer "):
                    supplied = header[7:]
                break
        if not supplied:
            qs = parse_qs(scope.get("query_string", b"").decode("latin-1"))
            supplied = (qs.get("token") or [""])[0]
        if not secrets.compare_digest(supplied, token):
            # Spell out what to do. A bare 401 on "/" (which browsers and
            # favicon requests hit constantly) reads like a broken server.
            body = json.dumps({
                "error": "unauthorized",
                "hint": "Append ?token=<your MCP_TOKEN> to the URL, or send "
                        "an 'Authorization: Bearer <token>' header.",
                "endpoint": "MCP clients connect to /mcp, not /",
            }).encode()
            await send({
                "type": "http.response.start",
                "status": 401,
                "headers": [
                    (b"content-type", b"application/json"),
                    (b"content-length", str(len(body)).encode()),
                ],
            })
            await send({"type": "http.response.body", "body": body})
            return

        is_sse = False

        async def send_wrapper(message: dict) -> None:
            nonlocal is_sse
            if message["type"] == "http.response.start":
                is_sse = any(
                    k == b"content-type" and b"text/event-stream" in v
                    for k, v in message.get("headers", [])
                )
            elif is_sse and message["type"] == "http.response.body" and message.get("body"):
                message = {**message, "body": _add_token_to_endpoint(message["body"])}
            await send(message)

        await app(scope, receive, send_wrapper)

    return gated


def _stable_subdomain() -> str:
    """Requested localtunnel hostname. Best-effort only — see below."""
    return os.environ.get("ONSHAPE_TUNNEL_SUBDOMAIN", "").strip()


def _ngrok_domain() -> str:
    """Reserved ngrok domain. Unlike localtunnel subdomains this is
    guaranteed: the domain is bound to your account, so the URL is
    genuinely the same every run. Free tier includes one.
    """
    return os.environ.get("ONSHAPE_NGROK_DOMAIN", "").strip()


def serve_sse(host: str, port: int, token: str, streamable: bool = True) -> None:
    """Serve MCP behind a shared-secret check.

    Streamable HTTP by default. The older SSE transport holds one long
    response open for every server->client message, and Cloudflare Quick
    Tunnels buffer that response indefinitely: the endpoint returns 200
    and then zero bytes forever, so no client can finish a handshake
    through a tunnel. Streamable HTTP answers over ordinary POSTs, which
    proxies pass straight through.
    """
    import uvicorn

    from .server import mcp
    from . import selfupdate  # noqa: F401  — registers the version/update tools

    app = mcp.streamable_http_app() if streamable else mcp.sse_app()
    uvicorn.run(require_token(app, token), host=host, port=port, log_level="info")


def find_tunnel_binary() -> tuple[str, list[str]] | None:
    """Pick a tunnel tool.

    localtunnel wins when a stable subdomain is requested, because it is
    the only free option here that can hand back the SAME hostname every
    run. Cloudflare Quick Tunnels always mint a random one, which meant
    re-pasting the URL into ChatGPT after every restart.
    """
    # ngrok first when a reserved domain is configured: it is the only
    # option here that actually guarantees the hostname. localtunnel
    # treats --subdomain as a request and silently hands back a random
    # name when it is taken, which is indistinguishable from working
    # until the connector breaks.
    ng = shutil.which("ngrok")
    if _ngrok_domain() and ng:
        return ("ngrok", [ng, "http", f"--url=https://{_ngrok_domain()}"])

    npx = shutil.which("npx")
    if _stable_subdomain() and npx:
        return ("localtunnel", [npx, "-y", "localtunnel", "--port"])

    cf = shutil.which("cloudflared")
    if cf:
        return ("cloudflared", [cf, "tunnel", "--url"])

    if npx:
        return ("localtunnel", [npx, "-y", "localtunnel", "--port"])

    return None


def _port_is_free(host: str, port: int) -> bool:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        try:
            s.bind((host, port))
            return True
        except OSError:
            return False


def run_tunnel_and_server(port: int = 8000, host: str = "127.0.0.1") -> None:
    """Start the MCP SSE server and attach an auto-tunnel for web AIs."""
    # A tunnel puts this on the public internet. An unguessable URL is not
    # authentication, so mint a token if the user hasn't set one.
    # stdout is block-buffered when piped, which swallows the banner below
    # until the process exits — exactly when you need to read the URL.
    sys.stdout.reconfigure(line_buffering=True)

    pinned = bool(settings.mcp_token)
    token = settings.mcp_token or secrets.token_urlsafe(24)
    # Only the tunnel process needs to reach the server; binding the
    # loopback keeps it off the LAN as well.
    host = "127.0.0.1"

    # Check before announcing anything. Otherwise a port clash prints a
    # celebratory public URL for a server that never came up.
    if not _port_is_free(host, port):
        raise SystemExit(
            f"Port {port} is already in use — another `onshape-mcp share` is probably running.\n"
            f"Reuse that one, stop it with Ctrl+C, or pick another port:\n"
            f"    onshape-mcp share --port {port + 1}"
        )

    tunnel_info = find_tunnel_binary()
    if not tunnel_info:
        print("=" * 68)
        print("⚠ No tunneling tool (cloudflared or npx) found on your system.")
        print("To enable instant web sharing, install cloudflared:")
        print("  • Mac:     brew install cloudflared")
        print("  • Linux:   sudo apt install cloudflared  (or download binary)")
        print("  • Windows: winget install Cloudflare.cloudflared")
        print("=" * 68)
        print(f"Starting local MCP server at http://{host}:{port}/mcp?token={token}")
        serve_sse(host, port, token)
        return

    tunnel_type, tunnel_cmd = tunnel_info
    local_url = f"http://{host}:{port}"

    print("=" * 68)
    print("   🌐 Onshape MCP — Instant Web Sharing & ChatGPT Connector")
    print("=" * 68)
    print(f"Starting local SSE engine on port {port}...")

    # Start the tunnel process in the background
    if tunnel_type == "cloudflared":
        cmd = [*tunnel_cmd, local_url]
    elif tunnel_type == "ngrok":
        cmd = [*tunnel_cmd, str(port), "--log=stdout"]
    else:
        cmd = [*tunnel_cmd, str(port)]
        if _stable_subdomain():
            cmd += ["--subdomain", _stable_subdomain()]

    tunnel_proc = subprocess.Popen(
        cmd,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
    )

    public_url: str | None = None
    start_time = time.time()

    # Read output to capture the public URL
    def _read_stream(stream: Any) -> None:
        nonlocal public_url
        if not stream:
            return
        for line in iter(stream.readline, ""):
            if not line:
                break
            # Cloudflare pattern
            m_cf = re.search(r"https://[a-zA-Z0-9-]+\.trycloudflare\.com", line)
            if m_cf:
                public_url = m_cf.group(0)
                break
            # Localtunnel pattern
            m_ng = re.search(r"https://[a-zA-Z0-9.-]+\.ngrok(?:-free)?\.(?:app|dev|io)", line)
            if m_ng:
                public_url = m_ng.group(0)
                break
            m_lt = re.search(r"https://[a-zA-Z0-9-]+\.loca\.lt", line)
            if m_lt:
                public_url = m_lt.group(0)
                break

    t_err = threading.Thread(target=_read_stream, args=(tunnel_proc.stderr,), daemon=True)
    t_out = threading.Thread(target=_read_stream, args=(tunnel_proc.stdout,), daemon=True)
    t_err.start()
    t_out.start()

    print("Requesting secure HTTPS tunnel from Cloudflare...")
    while public_url is None and (time.time() - start_time < 15):
        time.sleep(0.5)

    if public_url:
        sse_url = f"{public_url.rstrip('/')}/mcp?token={token}"
        print("\n" + "=" * 68)
        print("🎉 Your Onshape MCP is live on the internet:")
        print(f"\n👉 MCP URL:  \033[1;32m{sse_url}\033[0m\n")
        print("This URL drives YOUR logged-in Onshape session. Treat it as a")
        print("password: anyone who has it can edit your documents.\n")
        if pinned:
            print("Token: pinned from MCP_TOKEN in .env (stable across restarts).")
        else:
            print("Token: freshly minted — set MCP_TOKEN in .env to keep it stable.")
        want = _ngrok_domain() or _stable_subdomain()
        host_only = public_url.split("//")[-1]
        granted = host_only if _ngrok_domain() else host_only.split(".")[0]
        if want and granted == want:
            print(f"Hostname: PERMANENT ({want}). Paste this URL into ChatGPT once —")
            print("it survives restarts, so the connector keeps working and")
            print("onshape_mcp_update(restart=True) can update in place.\n")
        elif want:
            # Never claim permanence we did not get. localtunnel hands out
            # a random name when the requested subdomain is already taken,
            # and a URL that silently changed is the whole problem here.
            print(f"Hostname: NOT PERMANENT — asked for '{want}', got '{granted}'.")
            print("That subdomain is taken (possibly by your own earlier run — check")
            print("for a stray localtunnel process). Pick another name in")
            print("ONSHAPE_TUNNEL_SUBDOMAIN, or re-paste this URL for now.\n")
        else:
            print("Hostname: NEW random hostname every run, so you must re-paste this")
            print("URL into ChatGPT after each restart. Set ONSHAPE_TUNNEL_SUBDOMAIN")
            print("in .env for a permanent one.\n")
        print("1. ChatGPT: Settings > Connectors > Add, paste the full URL.")
        print("2. LibreChat / Open WebUI: add it under MCP servers.")
        print("=" * 68 + "\n")
    else:
        print("⚠ Tunnel did not return a public URL in 15s. Running locally.")
        print(f"Local endpoint: http://{host}:{port}/mcp?token={token}\n")

    try:
        serve_sse(host, port, token)
    finally:
        tunnel_proc.terminate()
        tunnel_proc.wait()
